# Generated by Django 3.1.7 on 2021-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botArena', '0003_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='source',
            field=models.FileField(default='bots_src/none.py', upload_to='bots_src/'),
        ),
    ]
