# Generated by Django 3.1.7 on 2021-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botArena', '0004_bot_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='source',
            field=models.FileField(default='game_src/none.py', upload_to='game_src/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='leader',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
