# Generated by Django 3.1.7 on 2021-03-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botArena', '0005_auto_20210311_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='url_source',
            field=models.URLField(default='https://spbstubotarena.s3.eu-central-1.amazonaws.com/mindfield.txt'),
        ),
    ]
