# Generated by Django 3.2 on 2021-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botArena', '0006_bot_url_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='interface',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
