# Generated by Django 3.2 on 2021-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botArena', '0007_game_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='Add description', max_length=40),
        ),
    ]
