# Generated by Django 3.2 on 2021-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botArena', '0008_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='long_description',
            field=models.FileField(default='game_description/base.txt', upload_to='game_description/'),
        ),
    ]
