# Generated by Django 3.2 on 2021-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botArena', '0009_game_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='all_games_count',
            field=models.IntegerField(default=1),
        ),
    ]
